global:
  scrape_interval: 15s

scrape_configs:

  - job_name: nginx-exporter
    static_configs:
    - targets: ['nginx-exporter:9113']

  - job_name: 'python-app'
    static_configs:
    - targets: ['app:8000']
 
  - job_name: 'python-flask-exporter'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['app:5000']

     